// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQmN58ui7dPXQT3NpBldWmrGldP48kKDY',
    appId: '1:449638453525:web:f703f5b42c11384a2a991c',
    messagingSenderId: '449638453525',
    projectId: 'athenna-path',
    authDomain: 'athenna-path.firebaseapp.com',
    storageBucket: 'athenna-path.firebasestorage.app',
    measurementId: 'G-RW31KEZY1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoMgI1BcJ7uw1BTAIIRMDpH7ha7tyBqYE',
    appId: '1:449638453525:android:f7712c698b497a232a991c',
    messagingSenderId: '449638453525',
    projectId: 'athenna-path',
    storageBucket: 'athenna-path.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCg4_0hVZucmiPR6pFKdgyySGwk710McM',
    appId: '1:449638453525:ios:5c0eadbb36a1436e2a991c',
    messagingSenderId: '449638453525',
    projectId: 'athenna-path',
    storageBucket: 'athenna-path.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCg4_0hVZucmiPR6pFKdgyySGwk710McM',
    appId: '1:449638453525:ios:5c0eadbb36a1436e2a991c',
    messagingSenderId: '449638453525',
    projectId: 'athenna-path',
    storageBucket: 'athenna-path.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQmN58ui7dPXQT3NpBldWmrGldP48kKDY',
    appId: '1:449638453525:web:9a9d2ce5238ca1a62a991c',
    messagingSenderId: '449638453525',
    projectId: 'athenna-path',
    authDomain: 'athenna-path.firebaseapp.com',
    storageBucket: 'athenna-path.firebasestorage.app',
    measurementId: 'G-9VD9J66FL6',
  );
}
